id: P3E2FB553
initial_creation_type: input
source_metadata:
  title: Prajñāpāramitāhṛdayasūtra
  language: bo
  volumes:
    5387f0aa2dec4ba4a21c7f73100b2238:
      title: Complete text
      base_file: Complete text.txt
      work_id: WC6B0BC53
  chapter_to_tile: {}
created_at: '2022-03-02T08:59:43.148118'
last_modified_at: '2022-03-02T08:59:43.148132'
